# Generated by Django 4.1.1 on 2022-11-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.TextField(max_length=25),
        ),
    ]
